# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:erbium

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

        environment:
          FIREBASE_TOKEN: $FIREBASE_TOKEN
          MAILERLIGHT_TOKEN: $MAILERLIGHT_TOKEN

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            - v2-dependencies-{{ checksum "functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn --cwd "functions" install

      - save_cache:
          paths:
            - functions/node_modules
          key: v2-dependencies-{{ checksum "functions/package.json" }}

      # run tests!
      - run: yarn test

      # - run:
      #     name: Build
      #     command: npm run generate

      # - run:
      #     name: Firebase Deploy
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
